'use strict';
// Turns findings.json into the master defect list, grouped by card.
const fs = require('fs');
const L = require('./lib.js');
const { people } = L.load();
const F = JSON.parse(fs.readFileSync(process.argv[2] || require('path').join(__dirname, 'findings.json'), 'utf8'));

// The Phase 1 card list lives in checks/priority-cards.json, which is git-ignored:
// it is a list of real people and does not belong in the repo's plaintext layer.
const P1F = require('path').join(__dirname, 'priority-cards.json');
const PHASE1 = fs.existsSync(P1F) ? JSON.parse(fs.readFileSync(P1F, 'utf8')) : [];
const CHECKNAME = {
  C1: 'hedge/assert conflict', C2: 'source-support', C2x: 'cross-card citation (verify)',
  C3: 'pin certainty', C4: 'arithmetic', C4q: 'arithmetic (quoted — verify, do not correct)',
  C4w: 'arithmetic worksheet', C5: 'cross-card claim index', C6: 'EN/FR parity',
  C6h: 'EN/FR wording queue', C7: 'tooltip shape', C8: 'gazetteer distance', X9: 'typography',
  X10: 'editorial machinery', X11: 'headline duplication', X12: 'unused source',
  X13: 'family-count worksheet', X13b: 'family-count contradiction'
};
const SEVRANK = { high: 0, med: 1, review: 2, low: 3 };

const byCard = new Map();
for (const f of F) {
  if (!byCard.has(f.card)) byCard.set(f.card, []);
  byCard.get(f.card).push(f);
}
const weight = f => ({ high: 10, med: 4, review: 2, low: 1 })[f.sev];
const cards = [...byCard.entries()].map(([card, fs_]) => ({
  card, fs: fs_.sort((a, b) => SEVRANK[a.sev] - SEVRANK[b.sev] || a.check.localeCompare(b.check)),
  score: fs_.reduce((a, f) => a + weight(f), 0),
  phase1: PHASE1.includes(card)
}));
cards.sort((a, b) => (b.phase1 - a.phase1) || (b.score - a.score));

const esc = s => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const out = [];
const counts = {};
F.forEach(f => { counts[f.check] = counts[f.check] || { high: 0, med: 0, review: 0, low: 0 }; counts[f.check][f.sev]++; });

out.push('# Master defect list — machine checks, 7 August 2026');
out.push('');
out.push(`Generated by \`checks/run.js\` over all ${people.length} cards of the uncommitted local \`data.json\`.`);
out.push(`**${F.length} findings on ${byCard.size} cards.** Nothing has been edited.`);
out.push('');
out.push('| Check | What it tests | high | med | review | low |');
out.push('|---|---|--:|--:|--:|--:|');
for (const [k, n] of Object.entries(counts).sort())
  out.push(`| ${k} | ${CHECKNAME[k] || ''} | ${n.high || ''} | ${n.med || ''} | ${n.review || ''} | ${n.low || ''} |`);
out.push('');
out.push('Severity: **high** = the machine believes this is wrong. **med** = a real inconsistency, needs a reader. ' +
  '**review** = a worksheet item the machine cannot close on its own (quoted text, off-card term, deliberate non-drawn kin). ' +
  '**low** = style/convention.');
out.push('');
out.push('**Measured precision.** All 60 high-severity findings from the previous build were read by four independent ' +
  'cold auditors who had seen none of this work: **38 TRUE, 22 FALSE, 0 UNSURE**. Every false-positive class they named ' +
  'was then fixed (`x:1` alternative pins excluded from the hedge comparison; a pin date inside its own span accepted; ' +
  'published and institutional sources counted as documentary; the life-event ordering reduced to the order that cannot ' +
  'repeat; source-count assertions demoted to worksheet). Eleven of the 22 false positives disappear under those fixes, ' +
  'so the current high tier should run near **38/49 ≈ 78%**. It is not 100%: read the evidence line before editing.');
out.push('');
out.push('The one contested block: the four **Laura** C1 findings. The human cold review (item 10) says the tooltip and ' +
  'the map pin assert the mother-reading flatly while the bio hedges it. All four machine auditors independently read the ' +
  'pin and tooltip as claiming only the *mother\'s* widowhood, which the bio also states flatly, and called them FALSE. ' +
  'Cory, or a fifth reader, settles this one.');
out.push('');
out.push('## What these checks cannot catch');
out.push('');
out.push('Stated plainly, so the Phase 1/2 readers know what they still have to do by eye:');
out.push('');
out.push([
  '- **Whether a source actually says what the card says it says.** C2 only tests that a source of the right *type* is on the card. Nobody has re-read the registers.',
  '- **A wrong fact stated consistently everywhere.** If the tooltip, bio, map note and pin all repeat the same error, every check passes.',
  '- **Prose quality** — a dangling modifier, a lost antecedent, a name the reader meets first in a sentence denying it. Cold-review items 23, 25, 26, 27, 28, 29, 31 are all of this kind and none is machine-detectable.',
  '- **Whether a hedge is the right hedge.** C1 finds a hedge on one field and certainty on another; it cannot tell which one is correct.',
  '- **Cross-card prose claims.** This tree has four Jean Georges, five Jean Martins and two Frédéric (Fritz). A name in prose is not an identifier, so C5 was rebuilt to use the drawn parent/child structure only. Cold-review items 1, 9, 15, 22 (one card asserting what another card holds) are flagged as `C2x` for a human, not resolved.',
  '- **Translation faithfulness.** C6h is a reading queue, not a verdict: EN and FR express negation and emphasis too differently for a word list to judge.',
  '- **Anything about a person the tree does not draw.** The family-count checks are worksheets for that reason.'
].join(String.fromCharCode(10)));
out.push('');
out.push('---');
out.push('');
out.push('## The high-severity list at a glance');
out.push('');
out.push('| card | field | finding |');
out.push('|---|---|---|');
for (const f of F.filter(x => x.sev === 'high').sort((a, b) => a.card.localeCompare(b.card)))
  out.push(`| ${esc(f.card)} | \`${esc(f.path)}\` | ${esc(f.msg)} |`);
out.push('');
out.push('---');
out.push('');

for (const c of cards) {
  if (c.card === '(tree)') continue;
  out.push(`## ${c.card}${c.phase1 ? '  ·  **[Phase 1]**' : ''}`);
  out.push('');
  out.push('| sev | check | field | finding |');
  out.push('|---|---|---|---|');
  for (const f of c.fs) {
    let extra = '';
    const d = f.detail || {};
    if (d.hedged) extra = `<br>· hedged: “${esc(d.hedged).slice(0, 170)}”<br>· flat: “${esc(d.flat).slice(0, 170)}”`;
    else if (d.sentence) extra = `<br>· “${esc(d.sentence).slice(0, 220)}”`;
    else if (d.text) extra = `<br>· “${esc(d.text).slice(0, 180)}”`;
    else if (d.en) extra = `<br>· EN “${esc(d.en).slice(0, 150)}”<br>· FR “${esc(d.fr).slice(0, 150)}”`;
    else if (d.row) extra = `<br>· \`${esc(JSON.stringify(d.row)).slice(0, 200)}\``;
    else if (d.label) extra = `<br>· ${esc(d.label).slice(0, 150)}`;
    if (d.matrix) extra += `<br>· computed: ${esc(d.matrix.join(' · ')).slice(0, 260)}`;
    if (d.candidates) extra += `<br>· computed: ${esc(d.candidates.join(' · ')).slice(0, 220)}`;
    if (d.nearest) extra += `<br>· gazetteer: ${esc(d.nearest.join(' · ')).slice(0, 220)}`;
    if (d.inventory) extra += `<br>· card holds: ${esc(d.inventory.join(' · ')).slice(0, 260)}`;
    if (d.sources) extra += `<br>· card holds: ${esc(d.sources.join(' · ')).slice(0, 260)}`;
    if (d.pins) extra += `<br>· pins: ${esc(d.pins.join(' · ')).slice(0, 200)}`;
    if (d.drawn) extra += `<br>· drawn: ${esc(d.drawn.join(' · ')).slice(0, 220)}`;
    if (d.sentences) extra += `<br>· ${esc(d.sentences.join(' | ')).slice(0, 300)}`;
    if (d.matches) extra += `<br>· matching sources: ${esc(d.matches.join(' · ')).slice(0, 220)}`;
    out.push(`| ${f.sev} | ${f.check} | \`${esc(f.path)}\` | ${esc(f.msg)}${extra} |`);
  }
  out.push('');
}

const tree = byCard.get('(tree)') || [];
if (tree.length) {
  out.push('## Cross-card (C5 claim index)');
  out.push('');
  out.push('| sev | where | finding |');
  out.push('|---|---|---|');
  for (const f of tree.sort((a, b) => SEVRANK[a.sev] - SEVRANK[b.sev]))
    out.push(`| ${f.sev} | \`${esc(f.path)}\` | ${esc(f.msg)}${f.detail && f.detail.sentence ? `<br>· “${esc(f.detail.sentence).slice(0, 200)}”` : ''} |`);
  out.push('');
}
fs.writeFileSync(process.argv[3] || require('path').join(__dirname, '..', 'MASTER-DEFECTS.md'), out.join('\n'));
console.log('cards reported:', cards.length, 'lines:', out.length);
